'use client';
import { useEffect, useRef, useState } from 'react';
import { useStudioTools } from './studio-tools';
import { ArrowDownToLine, ArrowUpRight, Box, Check, ChevronDown, CircleHelp, Grid2X2, Layers2, Maximize2, Minus, Moon, Sun, MousePointer2, Pause, Play, Plus, Rotate3D, RotateCcw, SlidersHorizontal, Sparkles, StepForward, X } from 'lucide-react';
import { Slider } from '@/components/ui/slider';
import { Switch } from '@/components/ui/switch';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import { defaults, type Settings } from './horse';
import type { mountHorse } from './horse';

const accessories=[{key:'saddle',title:'Saddle & cloth',sub:'Burgundy · No. 07',icon:Layers2},{key:'headgear',title:'Headgear',sub:'Leather bridle & reins',icon:Box},{key:'harness',title:'Harness',sub:'Breastplate & girth',icon:SlidersHorizontal},{key:'jockey',title:'Jockey',sub:'Forest racing silks',icon:Sparkles}] as const;
export default function Home(){
 const [settings,setSettings]=useState<Settings>(defaults),[ready,setReady]=useState(false),[error,setError]=useState(''),[phase,setPhase]=useState(0),[viewName,setViewName]=useState('Perspective'),[exporting,setExporting]=useState(false),[notice,setNotice]=useState(''),[help,setHelp]=useState(false);
 useStudioTools(setSettings);
 const host=useRef<HTMLDivElement>(null),stage=useRef<HTMLDivElement>(null),current=useRef(settings),engine=useRef<ReturnType<typeof mountHorse>|null>(null);current.current=settings;
 const set=<K extends keyof Settings>(key:K,value:Settings[K])=>setSettings(s=>({...s,[key]:value}));
 useEffect(()=>{if(window.matchMedia('(prefers-reduced-motion: reduce)').matches)setSettings(s=>({...s,playing:false}));let active=true;import('./horse').then(({mountHorse})=>{if(active&&host.current){try{engine.current=mountHorse(host.current,()=>current.current,setPhase);setReady(true);}catch{setError('The 3D viewer needs WebGL. Please enable hardware acceleration or try another browser.');}}}).catch(()=>setError('The 3D viewer could not load. Please refresh to try again.'));return()=>{active=false;engine.current?.destroy();engine.current=null;};},[]);
 useEffect(()=>{if(!notice)return;const id=setTimeout(()=>setNotice(''),3500);return()=>clearTimeout(id);},[notice]);
 useEffect(()=>{try{if(localStorage.getItem('betmakers-theme')==='light')setSettings(s=>({...s,darkMode:false}));}catch{}},[]);
 useEffect(()=>{document.documentElement.classList.toggle('dark',settings.darkMode);document.documentElement.style.colorScheme=settings.darkMode?'dark':'light';},[settings.darkMode]);
 function toggleTheme(){const darkMode=!settings.darkMode;set('darkMode',darkMode);try{localStorage.setItem('betmakers-theme',darkMode?'dark':'light');}catch{}}
 function cameraView(name:string){setViewName(name);engine.current?.view(name);}
 function reset(){setSettings(s=>({...defaults,darkMode:s.darkMode}));cameraView('Perspective');setNotice('Studio reset');}
 async function download(){if(!engine.current)return;setExporting(true);try{const blob=await engine.current.export();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`betmakers-horse-${settings.gait}-${String(Math.round(phase*100)).padStart(2,'0')}.png`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice('Image downloaded');}catch{setNotice('Could not download the image. Please try again.');}finally{setExporting(false);}}
 return <main className="studio">
 <header className="topbar"><a className="brand" href="/" aria-label="Betmakers Horse Studio home"><img src={settings.darkMode?"/betmakers-logo-dark.svg":"/betmakers-logo.svg"} width="180" height="72" alt="BetMakers"/></a><div className="breadcrumb"><span className="bread-line"/> HORSE STUDIO <span className="version">01</span></div><div className="top-actions"><span className="private-note"><span/> Your creative paddock</span><label className="theme-toggle"><span>{settings.darkMode?<Moon size={16}/>:<Sun size={16}/>}<span>Dark mode</span></span><Switch aria-label="Dark mode" checked={settings.darkMode} onCheckedChange={toggleTheme}/></label><button className="help-button" aria-label="Show viewer help" onClick={()=>setHelp(!help)}><CircleHelp size={19}/></button><button className="download" disabled={!ready||exporting} onClick={download}><ArrowDownToLine size={17}/><span>{exporting?'Exporting…':'Download image'}</span></button></div></header>
 <div className="workspace"><section className="viewer" ref={stage} aria-label="Horse model viewer"><div className="viewport" ref={host}/>
 <div className="scene-heading"><div className="eyebrow"><span/> LIVE 3D STUDIO</div><h1>Betmakers Horse Studio</h1><p>The thoroughbred, from every angle.</p></div>
 <div className="view-chip"><span className={ready?'status-dot':'status-dot loading'}/>{ready?'Live view':'Preparing model'}</div>
 {!ready&&<div className="loading-model" role="status">{error||'Preparing your thoroughbred…'}{error&&<button onClick={()=>window.location.reload()}>Try again</button>}</div>}
 <div className="stage-tools"><button title="Zoom in" aria-label="Zoom in" disabled={!ready} onClick={()=>engine.current?.zoom(1)}><Plus size={19}/></button><button title="Zoom out" aria-label="Zoom out" disabled={!ready} onClick={()=>engine.current?.zoom(-1)}><Minus size={19}/></button><span/><button className={settings.rotate?'is-active':''} title="Auto rotate" aria-label="Auto rotate" aria-pressed={settings.rotate} onClick={()=>set('rotate',!settings.rotate)}><Rotate3D size={19}/></button><button className={settings.grid?'is-active':''} title="Toggle floor grid" aria-label="Toggle floor grid" aria-pressed={settings.grid} onClick={()=>set('grid',!settings.grid)}><Grid2X2 size={18}/></button><button title="Reset camera" aria-label="Reset camera" onClick={()=>cameraView('Perspective')}><Maximize2 size={18}/></button></div>
 <div className="model-caption"><div className="model-no">07</div><div><strong>THE THOROUGHBRED</strong><span>Chestnut coat <i/> Sculpted model</span></div></div>
 <div className="orbit-hint"><MousePointer2 size={14}/><span>Drag to rotate</span><i/>Scroll to zoom</div>
 <div className="view-selector"><Select value={viewName} onValueChange={v=>v&&cameraView(v)}><SelectTrigger aria-label="Camera angle"><Box size={15}/><SelectValue/></SelectTrigger><SelectContent>{['Perspective','Side','Front','Rear','Underneath'].map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></div>
 {help&&<div className="help-card"><button aria-label="Close help" onClick={()=>setHelp(false)}><X size={17}/></button><h3>Make it your view</h3><p>Drag in any direction to orbit, including underneath. Scroll or pinch to zoom. Choose an animation, then pause and drag the timeline to capture a pose.</p><p>Switch accessories on or off and download exactly what’s on the stage.</p></div>}
 <div className="transport"><button className="play-main" disabled={!ready} aria-label={settings.playing?'Pause animation':'Play animation'} onClick={()=>set('playing',!settings.playing)}>{settings.playing?<Pause size={18} fill="currentColor"/>:<Play size={18} fill="currentColor"/>}</button><div className="transport-label"><strong>{settings.gait==='idle'?'Idle':settings.gait==='walk'?'Walk':'Run'}</strong><span>{settings.playing?'Playing':'Paused'}</span></div><div className="timeline"><Slider aria-label="Animation frame" value={[Math.round(phase*1000)]} max={1000} onValueChange={v=>setSettings(s=>({...s,playing:false,phase:Number(Array.isArray(v)?v[0]:v)/1000}))}/><div><span>00</span><span>MOTION CYCLE</span><span>100</span></div></div><button className="step" title="Advance one frame" aria-label="Advance one frame" onClick={()=>setSettings(s=>({...s,playing:false,phase:(phase+1/60)%1}))}><StepForward size={18}/></button><span className="frame-value">{Math.round(phase*100).toString().padStart(2,'0')}<small>%</small></span></div>
 </section>
 <aside className="controls"><div className="controls-title"><div><h2>Make it yours</h2><p>Every detail. Every motion.</p></div><button className="reset" aria-label="Reset all settings" title="Reset all settings" onClick={reset}><RotateCcw size={17}/></button></div>
 <section className="control-section"><div className="section-title"><h3>Motion</h3><span>01</span></div><div className="gait-options" role="group" aria-label="Animation"><button aria-pressed={settings.gait==='idle'} className={settings.gait==='idle'?'selected':''} onClick={()=>setSettings(s=>({...s,gait:'idle',playing:true,phase:0}))}><span className="motion-glyph idle-glyph">Ⅱ</span>Idle</button><button aria-pressed={settings.gait==='walk'} className={settings.gait==='walk'?'selected':''} onClick={()=>setSettings(s=>({...s,gait:'walk',playing:true,phase:0}))}><span className="motion-glyph">↝</span>Walk</button><button aria-pressed={settings.gait==='run'} className={settings.gait==='run'?'selected':''} onClick={()=>setSettings(s=>({...s,gait:'run',playing:true,phase:0}))}><span className="motion-glyph run-glyph">⇢</span>Run</button></div><div className="range-label"><label id="speed-label">Playback speed</label><span>{settings.speed.toFixed(2).replace(/0$/,'')}×</span></div><Slider aria-labelledby="speed-label" value={[settings.speed]} min={.25} max={2} step={.25} onValueChange={v=>set('speed',Number(Array.isArray(v)?v[0]:v))}/><div className="range-extents"><span>0.25×</span><span>2×</span></div></section>
 <section className="control-section"><div className="section-title"><h3>Pose</h3><span>02</span></div><Select value={settings.pose} onValueChange={v=>v&&setSettings(s=>({...s,pose:v,gait:'idle',playing:false}))}><SelectTrigger className="pose-select" aria-label="Pose preset"><SelectValue/></SelectTrigger><SelectContent>{['Natural','Alert','Grazing','Rearing'].map(p=><SelectItem key={p} value={p}>{p}</SelectItem>)}</SelectContent></Select><div className="range-label"><label id="head-label">Head position</label><span>{settings.head>0?'+':''}{settings.head}°</span></div><Slider aria-labelledby="head-label" value={[settings.head]} min={-20} max={30} step={1} onValueChange={v=>set('head',Number(Array.isArray(v)?v[0]:v))}/><div className="range-extents"><span>Raised</span><span>Lowered</span></div></section>
 <section className="control-section accessories"><div className="section-title"><h3>Accessories</h3><span>03</span></div>{accessories.map(({key,title,sub,icon:Icon})=><label className="accessory" key={key}><span className={'accessory-icon '+(settings[key]?'enabled':'')}><Icon size={19}/></span><span className="accessory-text"><strong>{title}</strong><small>{sub}</small></span><Switch aria-label={title} checked={settings[key]} onCheckedChange={v=>set(key,v)}/></label>)}</section>
 <div className="panel-footer"><div><span className="small-spark">✧</span><strong>Find your perfect frame.</strong></div><p>Pause the motion. Set the angle.<br/>Take the moment with you.</p><button onClick={download} disabled={!ready||exporting}>Export current view <ArrowUpRight size={16}/></button></div>
 </aside></div><footer className="bottom-bar"><span>BETMAKERS HORSE STUDIO <i/> An eye for equine detail.</span><span><span className="footer-dot"/> Rendered in real time <i/> PNG export</span></footer>
 {notice&&<div className="toast" role="status"><Check size={16}/>{notice}</div>}
 </main>;
}
