'use client';
import { Switch } from '@/components/ui/switch';
import { Select,SelectTrigger,SelectValue,SelectContent,SelectItem } from '@/components/ui/select';
import { Move,Rotate3D,Undo2,RotateCcw } from 'lucide-react';
import type { Settings } from './studio-settings';
export const jointNames=['Root','CG','Pelvis','Spine','Spine1','Spine2','Neck','Neck1','Neck2','Head','Jaw','L_Ear_00','R_Ear_00','L_Clavicle','L_UpperArm','l_Forearm','L_Hand','L_Finger0','R_Clavicle','R_UpperArm','R_Forearm','R_Hand','R_Finger0','Stomach','L_Thing','L_Calf','L_HorseLink','L_Foot','L_Toe0','R_Thing','R_Calf','R_HorseLink','R_Foot','R_Toe0','Tail01','Tail02','Tail03','Tail04','Tail05'];
export function jointLabel(name:string){const labels:Record<string,string>={Root:'Whole horse',CG:'Body',Pelvis:'Pelvis',Spine:'Lower spine',Spine1:'Mid spine',Spine2:'Chest',Neck:'Neck base',Neck1:'Mid neck',Neck2:'Upper neck',Head:'Head',Jaw:'Jaw',Stomach:'Belly'};if(labels[name])return labels[name];return name.replace(/^[Ll]_/, 'Left · ').replace(/^R_/, 'Right · ').replace('Clavicle','shoulder').replace('UpperArm','front upper leg').replace('Forearm','front knee').replace('Hand','front fetlock').replace('Finger0','front hoof').replace('Thing','hip').replace('Calf','stifle').replace('HorseLink','hock').replace('Foot','rear fetlock').replace('Toe0','rear hoof').replace('Ear_00','ear').replace(/Tail0(\d)/,'Tail $1');}
export function PosePanel({settings,ready,selected,set,togglePose,selectJoint,resetJoint,resetPose,undoPose}:{settings:Settings;ready:boolean;selected:string;set:<K extends keyof Settings>(k:K,v:Settings[K])=>void;togglePose:(v:boolean)=>void;selectJoint:(name:string)=>void;resetJoint:()=>void;resetPose:()=>void;undoPose:()=>void}){
 return <section className="control-section pose-section"><div className="section-title"><h3>Pose reference</h3></div><Select value={settings.reference} onValueChange={v=>v&&set('reference',v as Settings['reference'])}><SelectTrigger aria-label="Model display"><SelectValue>{({textured:"Textured",grey:"Grey mesh",depth:"Depth map",wireframe:"Wireframe"})[settings.reference]}</SelectValue></SelectTrigger><SelectContent><SelectItem value="textured">Textured</SelectItem><SelectItem value="grey">Grey mesh</SelectItem><SelectItem value="depth">Depth map</SelectItem><SelectItem value="wireframe">Wireframe</SelectItem></SelectContent></Select><p className="control-note">{settings.reference==='textured'?'Coat and cloth textures stay visible while posing.':settings.reference==='grey'?'Plain grey surfaces retain the shape and lighting.':settings.reference==='wireframe'?'See the mesh edges, including in your downloaded image.':'Near surfaces are lighter; far surfaces are darker. Black background, without lighting or textures.'}</p>
 <label className="setting-switch pose-toggle"><span>Manual pose mode</span><Switch aria-label="Manual pose mode" disabled={!ready} checked={settings.poseMode} onCheckedChange={togglePose}/></label>
 {settings.poseMode?<div className="manual-pose-controls"><p className="control-note">Click a pink joint, then drag an arrow or rotation ring. Drag empty space to orbit. G: move · R: rotate · Esc: deselect.</p><div className="pose-tool-buttons"><button aria-pressed={settings.poseTool==='translate'} className={settings.poseTool==='translate'?'selected':''} onClick={()=>set('poseTool','translate')}><Move size={16}/>Move</button><button aria-pressed={settings.poseTool==='rotate'} className={settings.poseTool==='rotate'?'selected':''} onClick={()=>set('poseTool','rotate')}><Rotate3D size={16}/>Rotate</button></div><Select value={selected||null} onValueChange={v=>v&&selectJoint(v)}><SelectTrigger aria-label="Select rig joint"><SelectValue placeholder="Select a joint"/></SelectTrigger><SelectContent>{jointNames.map(name=><SelectItem value={name} key={name}>{jointLabel(name)}</SelectItem>)}</SelectContent></Select><Select value={settings.poseSpace} onValueChange={v=>v&&set('poseSpace',v as Settings['poseSpace'])}><SelectTrigger aria-label="Transform axes"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="local">Local axes</SelectItem><SelectItem value="world">World axes</SelectItem></SelectContent></Select><label className="setting-switch"><span>Snap movement / rotation</span><Switch aria-label="Snap transforms" checked={settings.poseSnap} onCheckedChange={v=>set('poseSnap',v)}/></label><label className="setting-switch"><span>Show joints &amp; handles</span><Switch aria-label="Show joints and handles" checked={settings.showJoints} onCheckedChange={v=>set('showJoints',v)}/></label><div className="pose-action-buttons"><button onClick={undoPose}><Undo2 size={14}/>Undo</button><button disabled={!selected} onClick={resetJoint}>Reset joint</button><button onClick={resetPose}><RotateCcw size={14}/>Reset pose</button></div><p className="control-note">Edits start from the paused frame. Moving a joint also moves its children; rotate to bend a limb. Leaving pose mode restores the animation. Joint guides are excluded from downloads.</p></div>:<p className="control-note">Pause on a frame, then enable pose mode to adjust the horse’s joints.</p>}
 </section>;
}
