'use client';
import { useState, type Dispatch, type SetStateAction } from 'react';
import { ChevronDown, Plus, Trash2, Upload } from 'lucide-react';
import { Slider } from '@/components/ui/slider';
import { Switch } from '@/components/ui/switch';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import { Collapsible, CollapsibleTrigger, CollapsibleContent } from '@/components/ui/collapsible';
import { coats, fovToLens, lensToFov, lightingPreset, type Settings, type StudioLight } from './studio-settings';

function Range({label,value,min,max,step=1,unit='',onChange}:{label:string;value:number;min:number;max:number;step?:number;unit?:string;onChange:(n:number)=>void}){
 return <div className="studio-range"><div className="range-label"><span>{label}</span><output>{Number(value.toFixed(2))}{unit}</output></div><Slider aria-label={label} value={[value]} min={min} max={max} step={step} onValueChange={v=>onChange(Number(Array.isArray(v)?v[0]:v))}/></div>;
}
function Section({title,number,children}:{title:string;number:string;children:React.ReactNode}){
 return <Collapsible defaultOpen className="control-section studio-section"><CollapsibleTrigger className="section-title"><h3>{title}</h3><span>{number}<ChevronDown size={14}/></span></CollapsibleTrigger><CollapsibleContent><div className="section-body">{children}</div></CollapsibleContent></Collapsible>;
}
export function StudioPanel({settings,setSettings,ready,uploadCloth,resetCloth,clothName}:{settings:Settings;setSettings:Dispatch<SetStateAction<Settings>>;ready:boolean;uploadCloth:(file:File)=>Promise<void>;resetCloth:()=>void;clothName:string}){
 const [selected,setSelected]=useState('key'),[uploading,setUploading]=useState(false),[uploadError,setUploadError]=useState('');
 const preset=['Soft studio','Daylight','Dramatic'].find(name=>{const p=lightingPreset(name);return p.ambient===settings.ambient&&p.exposure===settings.exposure&&JSON.stringify(p.lights)===JSON.stringify(settings.lights);})||'Custom';
 const set=<K extends keyof Settings>(key:K,value:Settings[K])=>setSettings(s=>({...s,[key]:value}));
 const light=settings.lights.find(l=>l.id===selected)||settings.lights[0];
 const editLight=(patch:Partial<StudioLight>)=>{setSettings(s=>({...s,lights:s.lights.map(l=>l.id===light?.id?{...l,...patch}:l)}));};
 return <>
 <Section title="Camera" number="02"><div className="range-label"><span>Lens</span><output>{fovToLens(settings.fov).toFixed(1)} mm</output></div><div className="lens-options" role="group" aria-label="Lens presets">{[18,35,50,85].map(mm=><button key={mm} className={Math.abs(fovToLens(settings.fov)-mm)<.1?'selected':''} aria-pressed={Math.abs(fovToLens(settings.fov)-mm)<.1} onClick={()=>set('fov',lensToFov(mm))}>{mm} mm</button>)}</div><Range label="Field of view" value={settings.fov} min={15} max={80} step={.1} unit="°" onChange={v=>set('fov',v)}/><p className="control-note">Lens and vertical FOV are linked, using a 24 mm sensor height. Drag to orbit freely around the horse’s center.</p></Section>
 <Section title="Lighting" number="03"><Select value={preset} onValueChange={v=>{if(v&&v!=='Custom'){setSelected('key');setSettings(s=>({...s,...lightingPreset(v)}));}}}><SelectTrigger aria-label="Lighting preset"><SelectValue/></SelectTrigger><SelectContent>{['Soft studio','Daylight','Dramatic','Custom'].map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select>
 <Range label="Exposure" value={settings.exposure} min={.4} max={2.5} step={.05} onChange={v=>{set('exposure',v);}}/>
 <Range label="Ambient fill" value={settings.ambient} min={0} max={4} step={.1} onChange={v=>{set('ambient',v);}}/>
 <div className="light-list-heading"><span>Lights <small>{settings.lights.length}/6</small></span><button className="text-action" disabled={settings.lights.length>=6} onClick={()=>{const id=crypto.randomUUID();setSettings(s=>({...s,lights:[...s.lights,{id,name:`Light ${s.lights.length+1}`,enabled:true,color:'#ffffff',intensity:2,x:0,y:5,z:4}]}));setSelected(id);}}><Plus size={14}/>Add light</button></div>
 <div className="light-pills" role="group" aria-label="Select light">{settings.lights.map(l=><button key={l.id} aria-pressed={light?.id===l.id} className={light?.id===l.id?'selected':''} onClick={()=>setSelected(l.id)}><i style={{background:l.enabled?l.color:'#666'}}/>{l.name}</button>)}</div>
 {light&&<div className="light-editor"><div className="light-editor-title"><label><Switch aria-label={`Enable ${light.name}`} checked={light.enabled} onCheckedChange={enabled=>editLight({enabled})}/><span>{light.name}</span></label><button className="icon-action" aria-label={`Remove ${light.name}`} onClick={()=>{set('lights',settings.lights.filter(l=>l.id!==light.id));}}><Trash2 size={15}/></button></div><label className="light-color">Color<input aria-label={`${light.name} color`} type="color" value={light.color} onChange={e=>editLight({color:e.target.value})}/></label><Range label="Light intensity" value={light.intensity} min={0} max={8} step={.1} onChange={intensity=>editLight({intensity})}/>
 {(['x','y','z'] as const).map(axis=><Range key={axis} label={{x:'Position X · left / right',y:'Position Y · height',z:'Position Z · front / back'}[axis]} value={light[axis]} min={-10} max={10} step={.1} onChange={value=>editLight({[axis]:value})}/>)}<p className="control-note">Each light points toward the horse’s center.</p></div>}
 <label className="setting-switch"><span>Show light guides</span><Switch aria-label="Show light guides" checked={settings.lightHelpers} onCheckedChange={v=>set('lightHelpers',v)}/></label><p className="control-note">Guides are hidden in downloaded images.</p></Section>
 <Section title="Horse coat" number="04"><Select value={settings.coat} onValueChange={v=>v&&set('coat',v as Settings['coat'])}><SelectTrigger aria-label="Horse coat"><SelectValue/></SelectTrigger><SelectContent>{coats.map(c=><SelectItem value={c} key={c}>{c}</SelectItem>)}</SelectContent></Select><p className="control-note">Color variants of your Blender horse.</p></Section>
 <Section title="Saddlecloth" number="05"><div className="cloth-status"><span>Material</span><strong>Matte woven textile</strong></div><label className={`upload-cloth ${!ready||uploading?'disabled':''}`}><Upload size={17}/>{uploading?'Applying image…':'Upload cloth image'}<input type="file" accept="image/png,image/jpeg,image/webp" disabled={!ready||uploading} onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;setUploadError('');setUploading(true);try{await uploadCloth(file);}catch(error){setUploadError(error instanceof Error?error.message:'Could not load that image.');}finally{setUploading(false);}}}/></label><p className="control-note">PNG, JPG or WebP · up to 20 MB.<br/>Use a 2:1 image with the two sides placed side by side. Applied in this browser session.</p>{clothName&&<div className="uploaded-file"><span title={clothName}>{clothName}</span><button className="text-action" onClick={()=>{resetCloth();setUploadError('');}}>Restore original</button></div>}{uploadError&&<p className="upload-error" role="alert">{uploadError}</p>}</Section>
 </>;
}
